// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.mongodb.async.init {
    exports com.mastfrog.mongodb.init;
    exports com.mastfrog.mongodb.migration;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Transitive detected by source scan
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.tests;

    // Sibling com.mastfrog/giulius-mongodb-async-3.0.0-dev
    requires com.mastfrog.giulius.mongodb.async;

    // Sibling com.mastfrog/jackson-3.0.0-dev
    requires com.mastfrog.jackson;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    requires com.mastfrog.util.function;

    // derived from com.fasterxml.jackson.core/jackson-annotations-0.0.0-? in com/fasterxml/jackson/core/jackson-annotations/2.9.5/jackson-annotations-2.9.5.pom
    requires static com.fasterxml.jackson.annotation;
    requires com.fasterxml.jackson.databind;

    // Inferred from test-source-scan
    requires junit;
}
