// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.mongodb {
    exports com.mastfrog.giulius.mongo;
    exports com.mastfrog.giulius.mongo.util;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // derived from org.mongodb/mongo-java-driver-0.0.0-? in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires mongo.java.driver;

}
