open module com.mastfrog.giulius.mongodb {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.acteur.mongo;
    exports com.mastfrog.acteur.mongo.util;
    requires transitive com.mastfrog.giulius;

    // derived from org.mongodb/mongo-java-driver-3.12.11 in org/mongodb/mongo-java-driver/3.12.11/mongo-java-driver-3.12.11.pom
    requires transitive org.mongodb.mongo.java.driver;

}
