// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius {
    exports abcdefg;
    exports com.mastfrog.giulius;
    exports com.mastfrog.giulius.newanno;
    exports com.mastfrog.giulius.util;
    exports com.mastfrog.nstest;
    exports com.mastfrog.settings.ns1;
    exports com.mastfrog.xsettings;
    exports hijklmnop;
    
    requires meta.inf.loader;

    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;

    // Inferred from source scan

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-annotations-3.0.0-dev
    requires com.mastfrog.giulius.annotations;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/injection-reflection-indexer-3.0.0-dev:provided
    requires static com.mastfrog.injection.reflection.indexer;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // Inferred from source scan

    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;

    // Inferred from source scan

    // Sibling com.mastfrog/util-function-3.0.0-dev
    requires com.mastfrog.util.function;
    requires java.logging;

    // Inferred from test-source-scan
    requires junit;

}
