// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.annotation.processors {
    exports com.mastfrog.giulius.annotation.processors;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/annotation-tools-3.0.0-dev
    requires com.mastfrog.annotation.tools;

    // Inferred from source scan

    // Sibling com.mastfrog/util-fileformat-3.0.0-dev
    requires com.mastfrog.fileformat;
    requires java.compiler;
    provides javax.annotation.processing.Processor with
       com.mastfrog.giulius.annotation.processors.DefaultsAnnotationProcessor,
       com.mastfrog.giulius.annotation.processors.NamespaceAnnotationProcessor;

}
