open module com.mastfrog.smart.jar.merge {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.jarmerge;
    exports com.mastfrog.jarmerge.builtin;
    exports com.mastfrog.jarmerge.spi;
    exports com.mastfrog.jarmerge.support;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.giulius.settings;
    requires transitive com.mastfrog.util.fileformat;
    requires transitive com.mastfrog.util.strings;

}
