// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.injection.reflection.indexer {
    exports com.mastfrog.graal.annotation;
    exports com.mastfrog.graal.injection.processor;

    // Sibling com.mastfrog/annotation-processors-3.0.0-dev
    requires com.mastfrog.annotation.processors;

    // Sibling com.mastfrog/annotation-tools-3.0.0-dev
    requires transitive com.mastfrog.annotation.tools;

    // Sibling com.mastfrog/util-collections-3.0.0-dev
    requires com.mastfrog.collections;

    // Inferred from source scan
    // Sibling com.mastfrog/util-fileformat-3.0.0-dev
    requires com.mastfrog.fileformat;

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;
    requires java.compiler;
    
    requires com.fasterxml.jackson.core;
    requires com.fasterxml.jackson.databind;

    // Inferred from test-source-scan
    requires junit;
    provides javax.annotation.processing.Processor with
       com.mastfrog.graal.injection.processor.GraalInjectionProcessor;

}
