open module com.mastfrog.giulius.mongodb.async.init {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.mongodb.init;
    exports com.mastfrog.mongodb.migration;

    // derived from com.fasterxml.jackson.core/jackson-annotations-2.13.2 in com/fasterxml/jackson/core/jackson-annotations/2.13.2/jackson-annotations-2.13.2.pom
    requires transitive com.fasterxml.jackson.annotation;

    // derived from com.fasterxml.jackson.core/jackson-core-2.13.2 in com/fasterxml/jackson/core/jackson-core/2.13.2/jackson-core-2.13.2.pom
    requires transitive com.fasterxml.jackson.core;

    // derived from com.fasterxml.jackson.core/jackson-databind-2.13.2.2 in com/fasterxml/jackson/core/jackson-databind/2.13.2.2/jackson-databind-2.13.2.2.pom
    requires transitive com.fasterxml.jackson.databind;
    requires transitive com.mastfrog.acteur.mongo.async;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.giulius.mongodb.async;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.jackson;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
