open module com.mastfrog.giulius.settings {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.settings;
//    requires transitive com.mastfrog.util.collections;
    requires transitive com.mastfrog.util.preconditions;
    requires transitive com.mastfrog.util.streams;
    requires transitive com.mastfrog.util.strings;
}
