open module com.mastfrog.giulius.postgres.async {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.postgres.async;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.util.net;
    requires transitive com.mastfrog.util.streams;

    // derived from io.netty/netty-codec-dns-4.1.76.Final in io/netty/netty-codec-dns/4.1.76.Final/netty-codec-dns-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.dns;

    // derived from io.netty/netty-codec-http2-4.1.76.Final in io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.pom
    requires transitive io.netty.netty.codec.http2;

    // derived from io.netty/netty-handler-proxy-4.1.76.Final in io/netty/netty-handler-proxy/4.1.76.Final/netty-handler-proxy-4.1.76.Final.pom
    requires transitive io.netty.netty.handler.proxy;

    // derived from io.netty/netty-resolver-4.1.76.Final in io/netty/netty-resolver/4.1.76.Final/netty-resolver-4.1.76.Final.pom
    requires transitive io.netty.netty.resolver;

    // derived from io.netty/netty-resolver-dns-4.1.76.Final in io/netty/netty-resolver-dns/4.1.76.Final/netty-resolver-dns-4.1.76.Final.pom
    requires transitive io.netty.netty.resolver.dns;

    // derived from io.vertx/vertx-pg-client-4.2.7 in io/vertx/vertx-pg-client/4.2.7/vertx-pg-client-4.2.7.pom
    requires transitive io.vertx.vertx.pg.client;

}
