// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.annotations {
    exports com.mastfrog.giulius.annotations;

    // derived from com.google.inject/guice-0.0.0-?:compile in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.guice;

}
