// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.jdbc {
    exports com.mastfrog.giulius.jdbc;

    // derived from com.google.inject/guice-0.0.0-? in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires com.google.guice;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Sibling com.mastfrog/giulius-settings-3.0.0-dev
    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.streams;

    // derived from com.zaxxer/HikariCP-5.0.1:compile in com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.pom
    requires transitive com.zaxxer.hikari;
    requires java.sql;
}
