open module com.mastfrog.giulius.jdbc {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.jdbc;

    // derived from com.google.inject/guice-5.1.0 in com/google/inject/guice/5.1.0/guice-5.1.0.pom
    requires transitive com.google.inject.guice;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.settings;

    // derived from com.zaxxer/HikariCP-5.0.1 in com/zaxxer/HikariCP/5.0.1/HikariCP-5.0.1.pom
    requires transitive com.zaxxer.hikari;
    requires java.sql;

}
