open module com.mastfrog.giulius.threadpool {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.thread;
    exports com.mastfrog.giulius.thread.util;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.injection.reflection.indexer;
    requires java.logging;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

}
