// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.settings {
    exports com.mastfrog.settings;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Inferred from source scan
//    requires com.mastfrog.misc;

    // Inferred from source scan

    // Sibling com.mastfrog/util-preconditions-3.0.0-dev
    requires com.mastfrog.preconditions;

    // Inferred from source scan

    // Sibling com.mastfrog/util-streams-3.0.0-dev
    requires com.mastfrog.streams;

    // Inferred from source scan

    // Sibling com.mastfrog/util-strings-3.0.0-dev
    requires com.mastfrog.strings;

    // Inferred from test-source-scan
    requires transitive junit;

}
