open module com.mastfrog.giulius.mongodb.async {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.giulius.mongodb.async;
    requires transitive com.mastfrog.function;
    requires transitive com.mastfrog.giulius;
    requires transitive com.mastfrog.giulius.tests;
    requires transitive com.mastfrog.injection.reflection.indexer;
    requires transitive com.mastfrog.mongo.promises;
    requires transitive com.mastfrog.util.time;

    // derived from junit/junit-4.13.2 in junit/junit/4.13.2/junit-4.13.2.pom
    requires transitive junit.junit;

    // derived from org.mongodb/mongodb-driver-async-3.12.11 in org/mongodb/mongodb-driver-async/3.12.11/mongodb-driver-async-3.12.11.pom
    requires transitive org.mongodb.mongodb.driver.async;

}
