// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.mongodb.async {
    exports com.mastfrog.giulius.mongodb.async;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Sibling com.mastfrog/function-3.0.0-dev
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-3.0.0-dev
    requires com.mastfrog.giulius;

    // Transitive detected by source scan
    requires com.mastfrog.giulius.settings;

    // Sibling com.mastfrog/injection-reflection-indexer-3.0.0-dev:compile
    requires static com.mastfrog.injection.reflection.indexer;

    // Sibling com.mastfrog/mongo-promises-3.0.0-dev
    requires com.mastfrog.mongo.promises;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // Inferred from source scan
    // Sibling com.mastfrog/util-time-3.0.0-dev
    requires com.mastfrog.time;

    // Inferred from source scan
    requires com.mastfrog.util.function;
    requires com.mastfrog.giulius.tests;
    // Inferred from test-source-scan
    requires junit;
    requires org.mongodb.bson;
    requires org.mongodb.driver.core;
    // derived from org.mongodb/mongodb-driver-async-0.0.0-? in org/mongodb/mongodb-driver-async/3.12.11/mongodb-driver-async-3.12.11.pom
    requires org.mongodb.driver.async.client;
    requires javax.inject;
}
