// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.signalreload {
    exports com.mastfrog.signalreload;

    // Sibling com.mastfrog/giulius-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius;

    // Inferred from source scan
    requires com.mastfrog.preconditions;
    
    requires com.mastfrog.giulius.settings;
    
    requires java.logging;
    requires javax.inject;
    requires jdk.unsupported;
}
