open module com.mastfrog.signalreload {
// Generated by com.dv.sourcetreetool.impl.App

    exports com.mastfrog.signalreload;
    requires transitive com.mastfrog.giulius;
    requires java.logging;

}
