// Generated by com.dv.sourcetreetool.impl.App
open module com.mastfrog.giulius.postgres.async {
    exports com.mastfrog.giulius.postgres.async;

    // Inferred from source scan
    requires com.mastfrog.collections;

    // Inferred from source scan
    requires com.mastfrog.function;

    // Sibling com.mastfrog/giulius-3.0.0-dev

    // Transitive detected by source scan
    requires com.mastfrog.giulius;
    requires com.mastfrog.giulius.settings;

    // Inferred from source scan
    requires com.mastfrog.net;

    // Inferred from source scan
    requires com.mastfrog.preconditions;

    // Sibling com.mastfrog/util-streams-3.0.0-dev
    requires com.mastfrog.streams;

    // Inferred from source scan
    requires com.mastfrog.strings;

    // derived from io.netty/netty-codec-dns-4.1.76.Final in io/netty/netty-codec-dns/4.1.76.Final/netty-codec-dns-4.1.76.Final.pom
    requires io.netty.codec.dns;

    // derived from io.netty/netty-codec-http2-4.1.76.Final in io/netty/netty-codec-http2/4.1.76.Final/netty-codec-http2-4.1.76.Final.pom
    requires io.netty.codec.http2;

    // derived from io.netty/netty-handler-proxy-4.1.76.Final in io/netty/netty-handler-proxy/4.1.76.Final/netty-handler-proxy-4.1.76.Final.pom
    requires io.netty.handler.proxy;

    // derived from io.netty/netty-resolver-4.1.76.Final in io/netty/netty-resolver/4.1.76.Final/netty-resolver-4.1.76.Final.pom
    requires io.netty.resolver;

    // derived from io.netty/netty-resolver-dns-4.1.76.Final in io/netty/netty-resolver-dns/4.1.76.Final/netty-resolver-dns-4.1.76.Final.pom
    requires io.netty.resolver.dns;

    requires io.vertx.client.sql;
    // derived from io.vertx/vertx-pg-client-0.0.0-? in io/vertx/vertx-pg-client/4.2.7/vertx-pg-client-4.2.7.pom
    requires io.vertx.client.sql.pg;
    requires java.logging;
    requires io.vertx.core;

    // Inferred from test-source-scan
    requires org.junit.jupiter.api;
    requires org.junit.jupiter.engine;
    requires org.junit.jupiter.params;

}
